// Top-level build file where you can add configuration options common to all sub-projects/modules.

// Keep this block for old and annoying firebase plugins that don't support the new plugin DSL yet.
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.firebase:perf-plugin:1.4.2'  // Performance Monitoring plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.0'
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.navigation.safeargs) apply false
    alias(libs.plugins.oss.licenses) apply false
    alias(libs.plugins.kotlin.ksp) apply false
}

apply from: 'buildSrc/ktlint.gradle'

task clean(type: Delete) {
    delete rootProject.buildDir
}
