apply plugin: 'kotlin'
apply from: "$rootProject.projectDir/buildSrc/compile-kotlin.gradle"
apply from: "$rootProject.projectDir/buildSrc/compile-java.gradle"

dependencies {
    implementation project(path: ':telemetry-annotation')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.kotlin}"

    testImplementation "junit:junit:${Versions.junit4}"
    testImplementation 'com.google.testing.compile:compile-testing:0.15'
}
