apply from: "$rootProject.projectDir/buildSrc/android-library-base.gradle"
apply from: "$rootProject.projectDir/buildSrc/pmd.gradle"
apply from: "$rootProject.projectDir/buildSrc/checkstyle.gradle"

android {
    testOptions {
        unitTests.includeAndroidResources = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "androidx.appcompat:appcompat:${Versions.android_x_appcompat}"
    testImplementation "junit:junit:${Versions.junit4}"
    androidTestImplementation "androidx.test:runner:${Versions.test_runner}"
    androidTestImplementation "androidx.test.espresso:espresso-core:${Versions.espresso}"
    testImplementation "org.robolectric:robolectric:${Versions.robolectric}"
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle'
}
