apply from: "$rootProject.projectDir/buildSrc/android-library-base.gradle"
apply from: "$rootProject.projectDir/buildSrc/pmd.gradle"
apply from: "$rootProject.projectDir/buildSrc/checkstyle.gradle"

android {
    namespace 'org.mozilla.cachedrequestloader'

    testOptions {
        unitTests.includeAndroidResources = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':fileutils')
    implementation project(':threadutils')
    implementation project(':httptask')
    implementation project(':HttpRequest')

    implementation "androidx.appcompat:appcompat:${Versions.android_x_appcompat}"
    testImplementation "junit:junit:${Versions.junit4}"
    testImplementation "org.robolectric:robolectric:${Versions.robolectric}"
    androidTestImplementation "androidx.test.ext:junit:${Versions.test_ext}"
    androidTestImplementation "androidx.test:runner:${Versions.test_runner}"
    androidTestImplementation "androidx.test.espresso:espresso-core:${Versions.espresso}"
    androidTestImplementation "com.squareup.okhttp3:mockwebserver:${Versions.mockwebserver}"
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle'
}
