apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'com.google.android.gms.oss-licenses-plugin'
apply plugin: 'androidx.navigation.safeargs.kotlin'
apply from: '../buildSrc/pmd.gradle'
apply from: '../buildSrc/checkstyle.gradle'
apply from: '../buildSrc/ktlint.gradle'
apply from: 'buildscripts/l10n.gradle'
apply plugin: 'com.google.firebase.firebase-perf'
apply from: "$rootProject.projectDir/buildSrc/compile-android.gradle"
apply from: "$rootProject.projectDir/buildSrc/compile-kotlin.gradle"
apply plugin: 'com.google.devtools.ksp'

android {

    namespace 'org.mozilla.focus'

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    compileSdkVersion libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "dev.rocketscientists.rocket"
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.targetSdk.get().toInteger()
        versionCode libs.versions.versionCode.get().toInteger()
        versionName libs.versions.versionName.get()
        if (SystemEnv.auto_screenshot == "1") {
            testInstrumentationRunner "org.mozilla.focus.test.runner.ScreenshotTestRunner"
            testInstrumentationRunnerArguments clearPackageData: 'true'
        } else {
            // general UI test, using notAnnotation to filter out auto screenshot classes
            testInstrumentationRunner "org.mozilla.focus.test.runner.CustomTestRunner"
            testInstrumentationRunnerArguments clearPackageData: 'true', notAnnotation: 'org.mozilla.focus.annotation.ScreengrabOnly,androidx.test.filters.FlakyTest'
        }
        testInstrumentationRunnerArgument 'disableAnalytics', 'true'

        multiDexEnabled true

        vectorDrawables {
            useSupportLibrary false
            generatedDensities = []
        }

        def bitrise_build_number = System.getenv("BITRISE_BUILD_NUMBER")
        if (bitrise_build_number?.trim()) {
            versionCode bitrise_build_number.toInteger()
            versionNameSuffix "(" + bitrise_build_number + ")"
        }

        // used by Room, to test migrations
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }

        ksp {
            arg("projectRootDir", project.rootDir.toString())
        }
    }

    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }

    // We have a three dimensional build configuration:
    // BUILD TYPE (debug, release)

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            def userName = System.getenv("USER")
            applicationIdSuffix ".debug." + userName
            versionNameSuffix applicationIdSuffix
        }
        // Use a separate buildType for coverage: testCoverageEnabled produces slower code (4-5x slower
        // in places that I've benchmarked), and more importantly seems to break debugging with Android Studio
        // for some developers (i.e. variables can't be inspected or seen).
        coverage {
            initWith debug
            applicationIdSuffix ".coverage"
            testCoverageEnabled true
            matchingFallbacks = ["debug"]
        }
        // special build type to develop Firebase related stuff
        firebase {
            initWith debug
            applicationIdSuffix ".debug.firebase"

            versionNameSuffix applicationIdSuffix
            matchingFallbacks = ["debug"]
        }
    }

    testOptions {
        animationsDisabled = true
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
    }

    // used by Room, to test migrations
    sourceSets {
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

    flavorDimensions "product", "engine"

    productFlavors {
        focus {
            resConfigs Localization.KEPT_LOCALE
            dimension "product"
            FirebasePerformance {
                // Set this flag to 'false' to disable @AddTrace annotation processing and
                // automatic HTTP/S network request monitoring
                // for a specific build variant at compile time.
                instrumentationEnabled false
            }
        }

        preview {
            dimension "product"
            applicationIdSuffix ".beta"
            versionNameSuffix ".beta"
            FirebasePerformance {
                instrumentationEnabled true
            }
        }

        // We can build with two engines: webkit or gecko
        webkit {
            dimension "engine"
        }

    }

    variantFilter { variant ->
        def flavors = variant.flavors*.name
        // We only need a nightly release for now
        if (flavors.contains("preview") && variant.buildType.name != "release") {
            setIgnore(true)
        }
    }

    sourceSets {
        test {
            resources {
                // Make the default asset folder available as test resource folder. Robolectric seems
                // to fail to read assets for our setup. With this we can just read the files directly
                // and do not need to rely on Robolectric.
                srcDir "${projectDir}/src/main/assets/"
            }
        }

        preview {
            res.srcDir 'src/preview/res'
        }

        // used by Room, to test migrations
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }
}

dependencies {
    implementation project(':telemetry-annotation')
    ksp project(':telemetry-compiler')

    implementation project(':third_party:subsampling-scale-image-view')
    implementation libs.glide
    ksp libs.glide.ksp

    implementation project(':firebase')
    implementation project(':feature-tabs')
    implementation project(':HttpRequest')
    implementation project(':httptask')
    implementation project(':urlutils')
    implementation project(':fileutils')
    implementation project(':icon')
    implementation project(':logger')
    implementation project(':threadutils')
    implementation project(':cachedrequestloader')
    implementation project(':permissionhandler')
    implementation project(':strictmodeviolator')

    implementation libs.kotlin.stdlib.jdk8
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.kotlin.test.junit

    implementation libs.google.android.material
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.appcompat
    implementation libs.androidx.cardview
    implementation libs.androidx.recyclerview
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.viewpager2
    implementation libs.androidx.preference.ktx
    implementation libs.androidx.palette.ktx
    implementation libs.androidx.core.ktx

    // Architecture components
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.process
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.navigation.fragment.ktx
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.paging.runtime.ktx
    implementation libs.androidx.work.runtime
    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler


    implementation libs.mozilla.components.browser.session
    implementation libs.mozilla.components.browser.domains
    implementation libs.mozilla.components.ui.autocomplete
    implementation libs.mozilla.components.lib.fetch.httpurlconnection
    implementation libs.mozilla.components.concept.fetch
    implementation libs.mozilla.components.concept.engine
    implementation libs.mozilla.components.browser.engine.system

    implementation libs.lottie

    // Dagger 2
    implementation libs.google.dagger
    ksp libs.google.dagger.compiler

    implementation libs.mozilla.components.concept.awesomebar
    implementation libs.mozilla.components.browser.awesomebar

    testImplementation libs.junit
    testImplementation libs.robolectric
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin

    testImplementation libs.json
    testImplementation libs.androidx.test.core
    testImplementation libs.androidx.arch.core.testing

    androidTestImplementation libs.mockito.core

    androidTestImplementation libs.androidx.annotation
    androidTestImplementation libs.androidx.room.testing
    androidTestImplementation libs.androidx.arch.core.testing
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.uiautomator
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation(libs.androidx.test.espresso.contrib) {
        exclude module: "protobuf-lite"
    }
    androidTestImplementation libs.androidx.test.espresso.idling.resource
    androidTestImplementation libs.androidx.test.espresso.intents
    androidTestImplementation libs.androidx.test.espresso.web
    androidTestImplementation libs.mockwebserver
    androidTestImplementation libs.falcon
    androidTestImplementation(libs.screengrab) {
        exclude group: 'com.android.support.test.uiautomator', module: 'uiautomator-v18'
    }

    // LeakCanary
    debugImplementation libs.leakcanary.android
    firebaseImplementation libs.leakcanary.android

    implementation libs.google.playCore
}

// There is a issue with Appcompat 1.1.0 which has the WebView crash on Android 5 devices.
// https://issuetracker.google.com/issues/141132133
// We downgraded the libraries to 1.1.0-rc1 and need to check and upgrade to 1.2.0 in the future.
configurations.all {
    resolutionStrategy {
        force "androidx.appcompat:appcompat:${libs.versions.android.x.appcompat.get()}"
    }
}

// -------------------------------------------------------------------------------------------------
// Generate blocklists
// -------------------------------------------------------------------------------------------------

def blockListOutputDir = 'src/webkit/res/raw'

task buildBlocklists(type: Copy) {
    from('../shavar-prod-lists') {
        include '*.json'
    }
    into blockListOutputDir

    // Android can't handle dashes in the filename, so we need to rename:
    rename 'disconnect-blacklist.json', 'blocklist.json'
    rename 'disconnect-entitylist.json', 'entitylist.json'
    // google_mapping.json already has an expected name
}

clean.doLast {
    file(blockListOutputDir).deleteDir()
}

tasks.whenTaskAdded { task ->
    def name = task.name
    if (name.contains("Webkit")) {
        task.dependsOn buildBlocklists
    }
}

// -------------------------------------------------------------------------------------------------
// Firebase: Read config from environment variable (Only release builds)
// -------------------------------------------------------------------------------------------------

android.applicationVariants.all { variant ->
    def variantName = variant.getName()
    if (variant.buildType.name == "release" || variant.buildType.name == "firebase") {
        variant.getAssembleProvider().configure() {
            it.doFirst {
                if (SystemEnv.google_app_id == null || SystemEnv.default_web_client_id == null ||
                        SystemEnv.firebase_database_url == null || SystemEnv.gcm_defaultSenderId == null ||
                        SystemEnv.google_api_key == null || SystemEnv.google_crash_reporting_api_key == null ||
                        SystemEnv.project_id == null) {
                    logger.warn("If you want to enable Firebase, please follow the steps:")
                    logger.warn("1. Download google-services.json and put it in the folder where you run below command.")
                    logger.warn("2. Run 'python./tools/firebase/firebase_setup.py' and follow the steps.\n")
                }
            }
        }
    }
}

tasks.whenTaskAdded { task ->
    if (name.contains("compile") || name.contains("ksp")) {
        task.dependsOn generatePreviewLocaleList
        task.dependsOn generateFocusLocaleList
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        kotlinOptions.allWarningsAsErrors = false
    }
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle', 'checkTelemetryDocDirty', 'ktlint'
}

task checkTelemetryDocDirty() {

    doLast {
        Process p = Runtime.getRuntime().exec("git diff ./docs/events.md ./docs/view.sql")
        p.waitFor()

        BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));

        StringBuilder sb = new StringBuilder()
        String line = ""
        while ((line = reader.readLine()) != null) {
            sb.append(line + "\n")
        }
        if (sb.length() > 0) {
            throw new GradleException("events.md is drity, please commit the change first.\n" + sb.toString())
        }
    }
}

// -------------------------------------------------------------------------------------------------
// Generate strings.xml with customized translated strings
// -------------------------------------------------------------------------------------------------

task updateCustomizedStrings(type: Exec) {
    commandLine 'python', '../tools/l10n/attach-local-strings.py'
}

import org.mozilla.rocket.CheckPermissionsTask

task checkPermissionsTask(type: CheckPermissionsTask) {
    def PERMISSIONS_FILE_NAME = "acceptable_permissions.txt"
    permissionsFilePath = "$project.projectDir/$PERMISSIONS_FILE_NAME"
    def ANDROID_SDK_ROOT = System.getenv("ANDROID_SDK_ROOT")
    aapt2DirPath = System.getenv("AAPT2_DIR_PATH") ?: "$ANDROID_SDK_ROOT/build-tools/$android.buildToolsVersion/"
    apkFilePaths = []
    doFirst {
        android.applicationVariants.all { variant ->
            variant.outputs.each { output ->
                def filePath = output.outputFile
                if (filePath.exists()) {
                    apkFilePaths.add(filePath)
                }
            }
        }
    }
}
