apply from: "$rootProject.projectDir/buildSrc/android-library-base.gradle"
apply from: "$rootProject.projectDir/buildSrc/pmd.gradle"
apply from: "$rootProject.projectDir/buildSrc/checkstyle.gradle"

android {
    namespace 'org.mozilla.icon'
    testOptions {
        unitTests.includeAndroidResources = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':urlutils')
    implementation libs.androidx.appcompat
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.espresso.core
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle'
}
