apply plugin: 'com.android.library'

android {
    compileSdkVersion Versions.compile_sdk

    defaultConfig {
        minSdkVersion Versions.min_sdk
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:${Versions.appcompat}"
    implementation "com.google.android.material:material:${Versions.material}"
    testImplementation "junit:junit:${Versions.junit4}"
    androidTestImplementation "androidx.test:runner:${Versions.test_runner}"
    androidTestImplementation "androidx.test.espresso:espresso-core:${Versions.espresso}"
}
