apply plugin: 'java-library'
apply from: "$rootProject.projectDir/buildSrc/pmd.gradle"
apply from: "$rootProject.projectDir/buildSrc/checkstyle.gradle"

checkstyle {
    configFile = "${project.rootDir}/quality/checkstyle.xml" as File
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle'
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"
