apply plugin: 'kotlin-android'
apply from: "$rootProject.projectDir/buildSrc/android-library-base.gradle"
apply from: "$rootProject.projectDir/buildSrc/compile-kotlin.gradle"
apply from: '../../../buildSrc/checkstyle.gradle'
apply from: '../../../buildSrc/pmd.gradle'

android {
    namespace 'org.mozilla.rocket.tabs'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.kotlin.stdlib.jdk8

    testImplementation libs.robolectric
    testImplementation libs.mockito.core
    testImplementation libs.junit

    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.espresso.idling.resource

    implementation libs.mozilla.components.browser.session
    implementation libs.mozilla.components.concept.engine
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle'
}
