name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip lxml babel
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build with Gradle
        run: ./gradlew "clean" "updateCustomizedStrings" "checkstyle" "assembleFocusWebkitDebug" "lint" "findbugs" "ktlint" "checkPermissionsTask" "--stacktrace" "--no-daemon"
