apply plugin: 'kotlin-android'
apply from: "$rootProject.projectDir/buildSrc/android-library-base.gradle"
apply from: "$rootProject.projectDir/buildSrc/compile-kotlin.gradle"
apply from: "$rootProject.projectDir/buildSrc/pmd.gradle"
apply from: "$rootProject.projectDir/buildSrc/checkstyle.gradle"

android {
    namespace 'org.mozilla.strictmodeviolator'
    testOptions {
        unitTests.includeAndroidResources = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation libs.kotlin.stdlib.jdk8
    implementation libs.androidx.appcompat
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.mockwebserver
}

afterEvaluate {
    check.dependsOn 'pmd', 'checkstyle'
}
